import Theme from '@/lib/theme'
import './globals.css'

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	)
}

// /<title data-rh="true">Glitch :･ﾟ✧</title>
